### ISSUE TITLE
Patch failed

### ISSUE THREAD

**Issue by makanaashish** [DemacMedia/magento-SUPEE8788-patcher#9]
1.9.2.4 Detected
CE Detected
Valid Version
Reverting 1533 Using PATCH_SUPEE-1533_EE_1.13.x_v1-2014-10-03-04-00-17.sh
1533 Does not appear to be applied
Checking if patch can be applied/reverted successfully...
ERROR: Patch can't be applied/reverted successfully.

patching file app/code/core/Mage/Adminhtml/Block/Dashboard/Graph.php
Hunk #1 FAILED at 444.
1 out of 1 hunk FAILED -- saving rejects to file app/code/core/Mage/Adminhtml/Block/Dashboard/Graph.php.rej
patching file app/code/core/Mage/Adminhtml/controllers/DashboardController.php
Hunk #1 FAILED at 92.
1 out of 1 hunk FAILED -- saving rejects to file app/code/core/Mage/Adminhtml/controllers/DashboardController.php.rej
Patch 3941 Not Needed for this version.
8788 Does not appear to be applied
Checking if patch can be applied/reverted successfully...
ERROR: Patch can't be applied/reverted successfully.

patching file app/code/core/Mage/Adminhtml/Block/Catalog/Product/Helper/Form/Gallery/Content.php
Hunk #1 FAILED at 34.
Hunk #2 FAILED at 44.
Hunk #3 FAILED at 65.
3 out of 3 hunks FAILED -- saving rejects to file app/code/core/Mage/Adminhtml/Block/Catalog/Product/Helper/Form/Gallery/Content.php.rej
patching file app/code/core/Mage/Adminhtml/Block/Cms/Wysiwyg/Images/Content/Uploader.php
Hunk #1 FAILED at 31.
1 out of 1 hunk FAILED -- saving rejects to file app/code/core/Mage/Adminhtml/Block/Cms/Wysiwyg/Images/Content/Uploader.php.rej
patching file app/code/core/Mage/Adminhtml/Block/Media/Uploader.php
Hunk #1 FAILED at 31.
1 out of 1 hunk FAILED -- saving rejects to file app/code/core/Mage/Adminhtml/Block/Media/Uploader.php.rej
patching file app/code/core/Mage/Adminhtml/Block/Urlrewrite/Category/Tree.php
Hunk #1 FAILED at 119.
1 out of 1 hunk FAILED -- saving rejects to file app/code/core/Mage/Adminhtml/Block/Urlrewrite/Category/Tree.php.rej
patching file app/code/core/Mage/Adminhtml/Model/System/Config/Backend/Serialized.php
Hunk #1 FAILED at 29.
1 out of 1 hunk FAILED -- saving rejects to file app/code/core/Mage/Adminhtml/Model/System/Config/Backend/Serialized.php.rej
patching file app/code/core/Mage/Adminhtml/controllers/DashboardController.php
Hunk #1 FAILED at 91.
1 out of 1 hunk FAILED -- saving rejects to file app/code/core/Mage/Adminhtml/controllers/DashboardController.php.rej
patching file app/code/core/Mage/Adminhtml/controllers/IndexController.php
Hunk #1 FAILED at 391.
1 out of 1 hunk FAILED -- saving rejects to file app/code/core/Mage/Adminhtml/controllers/IndexController.php.rej
patching file app/code/core/Mage/Adminhtml/controllers/Media/UploaderController.php
Hunk #1 FAILED at 43.
1 out of 1 hunk FAILED -- saving rejects to file app/code/core/Mage/Adminhtml/controllers/Media/UploaderController.php.rej
patching file app/code/core/Mage/Catalog/Helper/Image.php
Hunk #1 FAILED at 33.
Hunk #2 FAILED at 634.
2 out of 2 hunks FAILED -- saving rejects to file app/code/core/Mage/Catalog/Helper/Image.php.rej
patching file app/code/core/Mage/Catalog/etc/config.xml
Hunk #1 FAILED at 807.
1 out of 1 hunk FAILED -- saving rejects to file app/code/core/Mage/Catalog/etc/config.xml.rej
patching file app/code/core/Mage/Catalog/etc/system.xml
Hunk #1 FAILED at 211.
1 out of 1 hunk FAILED -- saving rejects to file app/code/core/Mage/Catalog/etc/system.xml.rej
patching file app/code/core/Mage/Centinel/Model/Api.php
Hunk #1 FAILED at 25.
Hunk #2 FAILED at 73.
Hunk #3 FAILED at 136.
3 out of 3 hunks FAILED -- saving rejects to file app/code/core/Mage/Centinel/Model/Api.php.rej
patching file app/code/core/Mage/Centinel/Model/Api/Client.php
patching file app/code/core/Mage/Core/Block/Abstract.php
Hunk #1 FAILED at 37.
Hunk #2 FAILED at 1289.
2 out of 2 hunks FAILED -- saving rejects to file app/code/core/Mage/Core/Block/Abstract.php.rej
patching file app/code/core/Mage/Core/Helper/Url.php
Hunk #1 FAILED at 51.
1 out of 1 hunk FAILED -- saving rejects to file app/code/core/Mage/Core/Helper/Url.php.rej
patching file app/code/core/Mage/Core/Model/Encryption.php
Hunk #1 FAILED at 98.
1 out of 1 hunk FAILED -- saving rejects to file app/code/core/Mage/Core/Model/Encryption.php.rej
patching file app/code/core/Mage/Core/Model/Input/Filter/MaliciousCode.php
Hunk #1 FAILED at 65.
1 out of 1 hunk FAILED -- saving rejects to file app/code/core/Mage/Core/Model/Input/Filter/MaliciousCode.php.rej
patching file app/code/core/Mage/Core/functions.php
Hunk #1 FAILED at 375.
1 out of 1 hunk FAILED -- saving rejects to file app/code/core/Mage/Core/functions.php.rej
patching file app/code/core/Mage/Customer/Block/Address/Book.php
Hunk #1 FAILED at 56.
1 out of 1 hunk FAILED -- saving rejects to file app/code/core/Mage/Customer/Block/Address/Book.php.rej
patching file app/code/core/Mage/Customer/controllers/AddressController.php
Hunk #1 FAILED at 163.
1 out of 1 hunk FAILED -- saving rejects to file app/code/core/Mage/Customer/controllers/AddressController.php.rej
patching file app/code/core/Mage/Dataflow/Model/Profile.php
Hunk #1 FAILED at 64.
Hunk #2 FAILED at 127.
2 out of 2 hunks FAILED -- saving rejects to file app/code/core/Mage/Dataflow/Model/Profile.php.rej
patching file app/code/core/Mage/Downloadable/Block/Adminhtml/Catalog/Product/Edit/Tab/Downloadable/Links.php
Hunk #1 FAILED at 32.
Hunk #2 FAILED at 242.
Hunk #3 FAILED at 251.
Hunk #4 FAILED at 270.
4 out of 4 hunks FAILED -- saving rejects to file app/code/core/Mage/Downloadable/Block/Adminhtml/Catalog/Product/Edit/Tab/Downloadable/Links.php.rej
patching file app/code/core/Mage/Downloadable/Block/Adminhtml/Catalog/Product/Edit/Tab/Downloadable/Samples.php
Hunk #1 FAILED at 32.
Hunk #2 FAILED at 148.
Hunk #3 FAILED at 158.
Hunk #4 FAILED at 171.
4 out of 4 hunks FAILED -- saving rejects to file app/code/core/Mage/Downloadable/Block/Adminhtml/Catalog/Product/Edit/Tab/Downloadable/Samples.php.rej
patching file app/code/core/Mage/Downloadable/Helper/File.php
Hunk #1 FAILED at 33.
Hunk #2 FAILED at 152.
2 out of 2 hunks FAILED -- saving rejects to file app/code/core/Mage/Downloadable/Helper/File.php.rej
patching file app/code/core/Mage/Oauth/Model/Server.php
Hunk #1 FAILED at 328.
Hunk #2 FAILED at 544.
2 out of 2 hunks FAILED -- saving rejects to file app/code/core/Mage/Oauth/Model/Server.php.rej
patching file app/code/core/Mage/Paygate/Model/Authorizenet.php
Hunk #1 FAILED at 1273.
Hunk #2 FAILED at 1543.
2 out of 2 hunks FAILED -- saving rejects to file app/code/core/Mage/Paygate/Model/Authorizenet.php.rej
patching file app/code/core/Mage/Payment/Block/Info/Checkmo.php
Hunk #1 FAILED at 70.
Hunk #2 FAILED at 80.
2 out of 2 hunks FAILED -- saving rejects to file app/code/core/Mage/Payment/Block/Info/Checkmo.php.rej
patching file app/code/core/Mage/Paypal/Model/Express/Checkout.php
patching file app/code/core/Mage/Paypal/Model/Resource/Payment/Transaction.php
Hunk #1 FAILED at 53.
1 out of 1 hunk FAILED -- saving rejects to file app/code/core/Mage/Paypal/Model/Resource/Payment/Transaction.php.rej
patching file app/code/core/Mage/Sales/Model/Resource/Order/Payment.php
Hunk #1 FAILED at 58.
1 out of 1 hunk FAILED -- saving rejects to file app/code/core/Mage/Sales/Model/Resource/Order/Payment.php.rej
patching file app/code/core/Mage/Sales/Model/Resource/Order/Payment/Transaction.php
Hunk #1 FAILED at 53.
1 out of 1 hunk FAILED -- saving rejects to file app/code/core/Mage/Sales/Model/Resource/Order/Payment/Transaction.php.rej
patching file app/code/core/Mage/Sales/Model/Resource/Quote/Payment.php
Hunk #1 FAILED at 51.
1 out of 1 hunk FAILED -- saving rejects to file app/code/core/Mage/Sales/Model/Resource/Quote/Payment.php.rej
patching file app/code/core/Mage/Sales/Model/Resource/Recurring/Profile.php
Hunk #1 FAILED at 54.
1 out of 1 hunk FAILED -- saving rejects to file app/code/core/Mage/Sales/Model/Resource/Recurring/Profile.php.rej
patching file app/code/core/Mage/Uploader/Block/Abstract.php
patching file app/code/core/Mage/Uploader/Block/Multiple.php
patching file app/code/core/Mage/Uploader/Block/Single.php
patching file app/code/core/Mage/Uploader/Helper/Data.php
patching file app/code/core/Mage/Uploader/Helper/File.php
patching file app/code/core/Mage/Uploader/Model/Config/Abstract.php
patching file app/code/core/Mage/Uploader/Model/Config/Browsebutton.php
patching file app/code/core/Mage/Uploader/Model/Config/Misc.php
patching file app/code/core/Mage/Uploader/Model/Config/Uploader.php
patching file app/code/core/Mage/Uploader/etc/config.xml
patching file app/code/core/Mage/Uploader/etc/jstranslator.xml
patching file app/code/core/Mage/Usa/Model/Shipping/Carrier/Dhl.php
Hunk #1 FAILED at 538.
Hunk #2 FAILED at 1037.
2 out of 2 hunks FAILED -- saving rejects to file app/code/core/Mage/Usa/Model/Shipping/Carrier/Dhl.php.rej
patching file app/code/core/Mage/Usa/Model/Shipping/Carrier/Dhl/International.php
Hunk #1 FAILED at 837.
Hunk #2 FAILED at 1411.
Hunk #3 FAILED at 1603.
3 out of 3 hunks FAILED -- saving rejects to file app/code/core/Mage/Usa/Model/Shipping/Carrier/Dhl/International.php.rej
patching file app/code/core/Mage/Usa/Model/Shipping/Carrier/Fedex.php
Hunk #1 FAILED at 604.
Hunk #2 FAILED at 663.
2 out of 2 hunks FAILED -- saving rejects to file app/code/core/Mage/Usa/Model/Shipping/Carrier/Fedex.php.rej
patching file app/code/core/Mage/Usa/Model/Shipping/Carrier/Ups.php
Hunk #1 FAILED at 937.
Hunk #2 FAILED at 1578.
Hunk #3 FAILED at 1636.
3 out of 3 hunks FAILED -- saving rejects to file app/code/core/Mage/Usa/Model/Shipping/Carrier/Ups.php.rej
patching file app/code/core/Mage/Usa/etc/config.xml
Hunk #1 FAILED at 114.
Hunk #2 FAILED at 169.
Hunk #3 FAILED at 219.
3 out of 3 hunks FAILED -- saving rejects to file app/code/core/Mage/Usa/etc/config.xml.rej
patching file app/code/core/Mage/Usa/etc/system.xml
Hunk #1 FAILED at 130.
Hunk #2 FAILED at 744.
Hunk #3 FAILED at 1264.
3 out of 3 hunks FAILED -- saving rejects to file app/code/core/Mage/Usa/etc/system.xml.rej
patching file app/code/core/Mage/Wishlist/Helper/Data.php
Hunk #1 FAILED at 274.
1 out of 1 hunk FAILED -- saving rejects to file app/code/core/Mage/Wishlist/Helper/Data.php.rej
patching file app/code/core/Mage/Wishlist/controllers/IndexController.php
Hunk #1 FAILED at 434.
1 out of 1 hunk FAILED -- saving rejects to file app/code/core/Mage/Wishlist/controllers/IndexController.php.rej
patching file app/code/core/Mage/XmlConnect/Block/Adminhtml/Mobile/Edit/Tab/Design.php
Hunk #1 FAILED at 95.
1 out of 1 hunk FAILED -- saving rejects to file app/code/core/Mage/XmlConnect/Block/Adminhtml/Mobile/Edit/Tab/Design.php.rej
patching file app/code/core/Mage/XmlConnect/Block/Adminhtml/Mobile/Edit/Tab/Design/Images.php
Hunk #1 FAILED at 31.
Hunk #2 FAILED at 116.
Hunk #3 FAILED at 168.
Hunk #4 FAILED at 186.
4 out of 4 hunks FAILED -- saving rejects to file app/code/core/Mage/XmlConnect/Block/Adminhtml/Mobile/Edit/Tab/Design/Images.php.rej
patching file app/code/core/Mage/XmlConnect/controllers/Adminhtml/MobileController.php
Hunk #1 FAILED at 337.
Hunk #2 FAILED at 1377.
2 out of 2 hunks FAILED -- saving rejects to file app/code/core/Mage/XmlConnect/controllers/Adminhtml/MobileController.php.rej
patching file app/design/adminhtml/default/default/layout/cms.xml
Hunk #1 FAILED at 82.
1 out of 1 hunk FAILED -- saving rejects to file app/design/adminhtml/default/default/layout/cms.xml.rej
patching file app/design/adminhtml/default/default/layout/main.xml
Hunk #1 FAILED at 171.
1 out of 1 hunk FAILED -- saving rejects to file app/design/adminhtml/default/default/layout/main.xml.rej
patching file app/design/adminhtml/default/default/layout/xmlconnect.xml
Hunk #1 FAILED at 75.
Hunk #2 FAILED at 104.
2 out of 2 hunks FAILED -- saving rejects to file app/design/adminhtml/default/default/layout/xmlconnect.xml.rej
patching file app/design/adminhtml/default/default/template/catalog/product/helper/gallery.phtml
Hunk #1 FAILED at 108.
Hunk #2 FAILED at 120.
2 out of 2 hunks FAILED -- saving rejects to file app/design/adminhtml/default/default/template/catalog/product/helper/gallery.phtml.rej
patching file app/design/adminhtml/default/default/template/cms/browser/content/uploader.phtml
Hunk #1 FAILED at 24.
1 out of 1 hunk FAILED -- saving rejects to file app/design/adminhtml/default/default/template/cms/browser/content/uploader.phtml.rej
patching file app/design/adminhtml/default/default/template/downloadable/product/edit/downloadable.phtml
Hunk #1 FAILED at 34.
Hunk #2 FAILED at 88.
Hunk #3 FAILED at 141.
Hunk #4 FAILED at 167.
Hunk #5 FAILED at 204.
5 out of 5 hunks FAILED -- saving rejects to file app/design/adminhtml/default/default/template/downloadable/product/edit/downloadable.phtml.rej
patching file app/design/adminhtml/default/default/template/downloadable/product/edit/downloadable/links.phtml
Hunk #1 FAILED at 28.
Hunk #2 FAILED at 137.
Hunk #3 FAILED at 161.
Hunk #4 FAILED at 282.
Hunk #5 FAILED at 291.
Hunk #6 FAILED at 301.
6 out of 6 hunks FAILED -- saving rejects to file app/design/adminhtml/default/default/template/downloadable/product/edit/downloadable/links.phtml.rej
patching file app/design/adminhtml/default/default/template/downloadable/product/edit/downloadable/samples.phtml
Hunk #1 FAILED at 27.
Hunk #2 FAILED at 89.
Hunk #3 FAILED at 161.
Hunk #4 FAILED at 171.
4 out of 4 hunks FAILED -- saving rejects to file app/design/adminhtml/default/default/template/downloadable/product/edit/downloadable/samples.phtml.rej
patching file app/design/adminhtml/default/default/template/media/uploader.phtml
Hunk #1 FAILED at 26.
1 out of 1 hunk FAILED -- saving rejects to file app/design/adminhtml/default/default/template/media/uploader.phtml.rej
patching file app/design/adminhtml/default/default/template/xmlconnect/edit/tab/design.phtml
Hunk #1 FAILED at 24.
Hunk #2 FAILED at 66.
Hunk #3 FAILED at 89.
Hunk #4 FAILED at 102.
Hunk #5 FAILED at 209.
Hunk #6 FAILED at 283.
Hunk #7 FAILED at 401.
Hunk #8 FAILED at 427.
Hunk #9 FAILED at 485.
9 out of 9 hunks FAILED -- saving rejects to file app/design/adminhtml/default/default/template/xmlconnect/edit/tab/design.phtml.rej
patching file app/etc/modules/Mage_All.xml
Hunk #1 FAILED at 275.
Hunk #2 FAILED at 397.
2 out of 2 hunks FAILED -- saving rejects to file app/etc/modules/Mage_All.xml.rej
patching file app/locale/en_US/Mage_Media.csv
patching file app/locale/en_US/Mage_Uploader.csv
patching file downloader/lib/Mage/HTTP/Client/Curl.php
Hunk #1 FAILED at 373.
1 out of 1 hunk FAILED -- saving rejects to file downloader/lib/Mage/HTTP/Client/Curl.php.rej
patching file js/lib/uploader/flow.min.js
patching file js/lib/uploader/fusty-flow-factory.js
patching file js/lib/uploader/fusty-flow.js
patching file js/mage/adminhtml/product.js
Hunk #1 FAILED at 34.
Hunk #2 FAILED at 56.
Hunk #3 FAILED at 113.
3 out of 3 hunks FAILED -- saving rejects to file js/mage/adminhtml/product.js.rej
patching file js/mage/adminhtml/uploader/instance.js
patching file lib/Unserialize/Parser.php
Hunk #1 FAILED at 34.
1 out of 1 hunk FAILED -- saving rejects to file lib/Unserialize/Parser.php.rej
patching file lib/Unserialize/Reader/Arr.php
Hunk #1 FAILED at 101.
1 out of 1 hunk FAILED -- saving rejects to file lib/Unserialize/Reader/Arr.php.rej
patching file lib/Unserialize/Reader/ArrValue.php
Hunk #1 FAILED at 84.
1 out of 1 hunk FAILED -- saving rejects to file lib/Unserialize/Reader/ArrValue.php.rej
patching file lib/Unserialize/Reader/Null.php
patching file skin/adminhtml/default/default/boxes.css
Hunk #1 FAILED at 78.
Hunk #2 FAILED at 1396.
2 out of 2 hunks FAILED -- saving rejects to file skin/adminhtml/default/default/boxes.css.rej
patching file skin/adminhtml/default/default/media/flex.swf
patching file skin/adminhtml/default/default/media/uploader.swf
patching file skin/adminhtml/default/default/media/uploaderSingle.swf
patching file skin/adminhtml/default/default/xmlconnect/boxes.css
Hunk #1 FAILED at 90.
1 out of 1 hunk FAILED -- saving rejects to file skin/adminhtml/default/default/xmlconnect/boxes.css.rej

**Comment by reztierk** [comment]
The patch is not applicable for 1.9.2.4 as the issues were addressed in 1.9.2.3  see https://magento.com/security/patches/supee-8788
